version: "3" 
services:

  route-master-jenkins:
    container_name: route-master-jenkins
    user: "${UID}:${GID}"
    image: route-master-jenkins
    build: .
    volumes:
      - $VOLUME_JENKINS_HOME:/var/jenkins_home
      - /var/run:/var/run:ro
    environment:
      - TZ=Asia/Seoul
      - JENKINS_OPTS="--prefix=/jenkins"
    ports:
      - "8080:8080"
      - "50000:50000"
    group_add:
      - ${DOCKER_GROUP}
