version: '3.9'
services:
  app:
    image: jenkins_practice
    container_name: jenkins
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"